### ISSUE TITLE
Vista de Servicios

### ISSUE THREAD

**Issue by fuf-herNef** [fuf-herNef/Moubi-vue#1]
Creación del componente vuejs para la vista de servicios, llamarlo ServicesCard.vue.  Tener en cuenta de crear el respectivo archivo json que contenga los datos del servicio. Nombre del JSON services.json
services: {
name:
img:
description:
}
agregar otros campos is asi lo desea.

**Comment by angelaa06** [comment]
Se creó el componente de Vue ServicesCard, donde se trabajó con bootstrap y se agregaron algunos estilos individuales.
